<?php

namespace Database\Seeders;

use App\Models\SurveyQuestion;
use App\Models\SurveyTemplate;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TemplateQuestionSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $user = User::query()->firstOrCreate(
                ['email' => 'admin@desa-wisata-bca.test'],
                [
                    'name' => 'Admin CSR',
                    'password' => 'password',
                ],
            );

            $template = SurveyTemplate::withTrashed()->firstOrNew([
                'title' => 'Instrumen Klasifikasi Desa/Kampung Wisata',
                'type' => 'village',
            ]);
            $shouldRestore = $template->exists && $template->trashed();

            $template->fill([
                'description' => 'Template pertanyaan hasil konversi dari template-question.pdf.',
                'status' => 'published',
                'created_by' => $user->id,
                'published_at' => now(),
            ]);
            $template->save();

            if ($shouldRestore) {
                $template->restore();
            }

            $template->questions()
                ->withTrashed()
                ->get()
                ->each(function (SurveyQuestion $question): void {
                    $question->options()->withTrashed()->forceDelete();
                    $question->forceDelete();
                });

            foreach ($this->rows() as $index => $row) {
                $question = $template->questions()->create([
                    'aspect' => $row['aspect'],
                    'code' => sprintf('Q%02d', $index + 1),
                    'question_text' => $row['question_text'],
                    'document_hint' => $row['document_hint'] ?: null,
                    'sort_order' => $index + 1,
                ]);

                foreach ($row['options'] as $optionIndex => $label) {
                    $question->options()->create([
                        'score' => $optionIndex + 1,
                        'label' => $label,
                        'sort_order' => $optionIndex + 1,
                    ]);
                }
            }
        });
    }

    /**
     * @return array<int, array{aspect: string, question_text: string, document_hint: string, options: array<int, string>}>
     */
    private function rows(): array
    {
        return collect(explode("\n", trim(self::SOURCE_ROWS)))
            ->map(function (string $line): array {
                [$aspect, $questionText, $documentHint, $options] = explode('|', $line);

                return [
                    'aspect' => $aspect,
                    'question_text' => $questionText,
                    'document_hint' => $documentHint,
                    'options' => explode('~', $options),
                ];
            })
            ->all();
    }

    private const SOURCE_ROWS = <<<'ROWS'
Kelembagaan|Pengelola Desa/Kampung Wisata memiliki struktur pengurus wisata (secara legal) dan disahkan oleh pihak terkait (tingkat desa, kabupaten/ provinsi). Dibuktikan dengan dokumen struktur kepengurusan berikut ketugasan yang diperankan masing-masing bagian.|SK Pengelola yang telah disahkan; Job Deskripsi|Belum ada legalitas pengelolaan Desa/Kampung Wisata.~Telah ada legalitas kepengurusan pariwisata di Desa/Kampung Wisata, NAMUN belum dilengkapi dengan dokumen pendukung.~Telah memiliki legalitas kepengurusan pariwisata di Desa/Kampung Wisata secara tertulis, NAMUN belum dilengkapi penjelasan tentang Tugas dan Fungsi.~Telah memiliki legalitas kepengurusan pariwisata di Desa/Kampung Wisata secara tertulis DAN sudah dilengkapi dengan penjelasan tentang Tugas dan Fungsi.
Kelembagaan|Sudah merumuskan dan menetapkan AD/ART yang berlaku kepada pengelola yang terlibat dalam aktivitas Desa/Kampung Wisata. Dibuktikan dengan dokumen AD/ART.|AD/ART yang telah disahkan pihak berwenang|Belum membuat dan menetapkan AD/ART.~Masih dalam proses pembuatan AD/ART.~Telah membuat dan menetapkan AD/ART, NAMUN belum dijalankan secara optimal.~Telah ada AD/ART dan telah menjalankan ketentuan seperti yang ditetapkan.
Kelembagaan|Terdapat pencatatan keuangan yang jelas dan transparan yang dilaporkan dalam jangka waktu tertentu. Dibuktikan dengan dokumen pencatatan keuangan.|Laporan keuangan baik secara manual maupun digital|Belum membuat atau memiliki catatan keuangan.~Sudah memiliki catatan keuangan, NAMUN belum dipisah dengan pengeluaran urusan rumah tangga.~Sudah melakukan pencatatan keuangan dengan rapi dan direkap dalam pembukuan secara manual. SUDAH dipisahkan dengan urusan rumah tangga.~Sudah memiliki pencatatan keuangan yang rapi, berkala, dan dilaporkan dalam pertemuan pengelola secara bertahap DAN dikelola secara digital.
Kelembagaan|Terdapat pencatatan kunjungan wisatawan di Desa/Kampung Wisata ( < 5 Tahun terakhir). Disajikan dengan tabel/ chart/ secara baik.|Data kunjungan wisatawan yang sudah dianalisis|Tidak ada pencatatan kunjungan wisatawan.~Ada pencatatan kunjungan wisatawan BELUM diolah menjadi grafik/chart sebagai bahan pelaporan.~Ada pencatatan kunjungan wisatawan. Tidak dipilah asal wisatawan, kegiatan yang dilakukan, BELUM diolah dalam chart/grafik.~Ada pencatatan kunjungan, tertulis secara detail, disertai grafik trend wisatawan sebagai hasil analisi data kunjungan.
Kelembagaan|Pengelola pariwisata memiliki dokumen perencanaan Desa/Kampung Wisata dan sudah ada yang dijalankan sebagian program yang direncanakan. Ada dokumen perencanaan pengembangan desa wisata berikut dengan bukti- bukti pelaksanaannya.|Dokumen perencanaan dan program kerja yang sudah dijalankan|Tidak ada dokumen perencanaan.~Sudah memiliki dokumen perencanaan, NAMUN belum dijalankan.~Sudah memiliki dokumen perencanaan, sudah menjalankan sebagian program yang direncanakan. NAMUN tidak ada bukti dokumentasi.~Sudah memiliki dokumen perencanaan, sudah ada yang dijalankan dan dibuktikan dengan dokumentasi.
Kelembagaan|Pengelola wisata secara rutin melakukan pertemuan Desa/Kampung Wisata. Dibuktikan dengan notulensi pertemuan.|Surat undangan rapat, daftar hadir, dan notulensi rapat|Tidak ada agenda pertemuan secara rutin.~Pertemuan dilakukan namun secara isidental, hanya jika diperlukan.~Pertemuan dilakukan secara rutin, NAMUN belum ada keterlibatan secara menyeluruh, hanya Pengurus Inti pariwisata, dan perwakilan pedukuhan.~Pertemuan dilakukan secara rutin, sudah ada pendokumentasian hasil pertemuan. DAN keterlibatan secara menyeluruh meliputi pengurus dan beberapa perwakilan pedukuhan/warga.
Kelembagaan|Adanya sistem pergantian kepengurusan yang dipilih melalui musyawarah yang jabatannya dibatasi dalam jangka waktu tertentu.|Dokumen rapat pemilihan dan pergantian kepengurusan|Tidak ada kesepakatan bahwa pengelola Desa/Kampung Wisata yang dipilih melalui musyawarah.~Terdapat pengambilan keputusan sepihak atau aklamasi saat pergantian kepengurusan.~Terdapat kesepakatan kepengurusan yang dipilih melalui musyawarah namun tidak diatur masa jabatannya.~Terdapat kesepakatan kepengurusan yang dipilih melalui musyawarah dan diatur pula masa jabatannya.
Kelembagaan|Terdapat keseimbangan/kesetaraan dalam komposisi pengelola Desa/Kampung Wisata berdasarkan kelompok usia dan gender.|Dokumen struktur pengelola yang mencatat komposisi secara detil|Tidak terdapat keseimbangan/kesetaraan berdasarkan kelompok usia dan gender dalam pencatatan komposisi struktur pengelola wisata.~Terdapat keseimbangan/kesetaraan berdasarkan kelompok usia atau gender dalam pengelola namun hanya disebutkan secara lisan.~Terdapat keseimbangan/kesetaraan berdasarkan kelompok usia atau gender (salah satu) dan tercatat.~Terdapat keseimbangan/kesetaraan berdasarkan kelompok usia dan gender dalam pencatatan komposisi struktur pengelola wisata.
Kelembagaan|Pengelola Desa/Kampung Wisata memiliki sistem untuk menampung masukan (saran,pesan,kesan) dari wisatawan.|Data feedback wisatawan, baik secara manual maupun digital|Tidak terdapat sistem untuk menampung feedback (saran, pesan, kesan) dari wisatawan.~Tidak terdapat sistem. Namun, terdapat feedback (saran, pesan, kesan) dari wisatawan disampaikan secara personal kepada pengelola.~Terdapat sistem untuk menampung feedback namun tidak tercatat (hanya secara lisan).~Terdapat sistem untuk menampung feedback (saran, pesan, kesan) dari wisatawan yang tercatat.
Kelembagaan|Dapat menyediakan pemandu lokal berbahasa asing jika kedatangan wisatawan asing (terdapat pengelola desa/kampung wisata yang bisa berbahasa asing menjadi nilai tambah).|Data jumlah pemandu wisata berbahasa asing, baik yang sudah tersertifikai maupun belum|Tidak memiliki pemandu lokal yang dapat berbahasa asing.~Tersedia pemandu wisata berbahasa asing, namun berasal dari luar Desa/Kampung Wisata.~Terdapat pemandu wisata berbahasa asing, NAMUN belum memiliki sertifikasi.~Terdapat pemandu wisata yang dapat berbahasa asing, sertidaknya dua bahasa asing dari Desa/Kampung Wisata setempat dan tersertifikasi.
KEMITRAAN|Desa/Kampung Wisata memiliki kemitraan dengan pemangku kepentingan pihak eksternal mencakup pentahelix (ABCGM). Kemitraan Desa/Kampung Wisata pada ranah operasional.|MoU dengan stakeholder eksternal|Memiliki kemitraan minimal 1 unsur pemangku kepentingan dan terdokumentasikan.~Memiliki kemitraan minimal 2 unsur pemangku kepentingan dan terdokumentasikan.~Memiliki kemitraan minimal 3 unsur pemangku kepentingan dan terdokumentasikan.~Memiliki kemitraan lebih dari 4 unsur pemangku kepentingan dan terdokumentasikan.
KEMITRAAN|Pengelola Desa/Kampung Wisata memiliki kemitraan dengan stakeholder internal (Perangkat Desa, Perangkat dukuh, Karang Taruna, PKK, KWT, LMDH). Dibuktikan dengan dokumen tertulis. Kemitraan Desa/Kampung Wisata dalam konteks operasional, diantaranya pengelolaan destinasi.|MoU dengan stakeholder internal|Belum memiliki kemitraan.~Sudah memiliki kemitraan.~Memiliki kemitraan NAMUN belum ada MoU-nya.~Memilki kemitraan dan sudah dituangkan dalam MoU.
KEMITRAAN|Sifat kemitraan dalam berkontribusi untuk pengembangan Desa/Kampung Wisata. Dibuktikan dengan bukti kemitraan.|Implementasi MoU dengan mitra|Mitra berkontribusi dalam SALAH SATU bentuk, yakni uang cash saja atau dalam wujud barang saja, NAMUN tidak terdokumentasikan.~Mitra berkontribusi dalam SALAH SATU bentuk, yakni uang cash saja atau dalam wujud barang saja, DAN sudah terdokumentasikan.~Mitra berkontribusi dalam bentuk uang cash DAN bentuk barang, NAMUN tidak terdokumentasikan.~Mitra berkontribusi dalam bentuk uang cash DAN bentuk barang, DAN terdokumentasikan.
KEMITRAAN|Kemitraan berlangsung jangka panjang dan berkelanjutan.|Implementasi MoU dengan mitra|Mitra berkontribusi secara temporer, dan tidak terdokumentasikan.~Mitra berkontribusi secara temporer dan terdokumentasikan.~Mitra berkontribusi secara berkelanjutan namun tidak terdokumentasikan.~Mitra berkontribusi secara berkelanjutan dan terdokumentasikan.
KEMITRAAN|Kemitraan berdampak pada peningkatan kualitas bidang ekonomi, sosial, budaya, dan lingkungan.|Implementasi MoU dengan mitra|Mitra berkontribusi pada peningkatan kualitas namun hanya 1 bidang dan terdokumentasi.~Mitra berkontribusi pada peningkatan kualitas pada 2 bidang dan sudah terdokumentasi.~Mitra berkontribusi pada peningkatan kualitas minimal 3 bidang dan terdokumentasi.~Mitra berkontribusi pada peningkatan kualitas 4 bidang, yakni ekonomi, sosial, budaya, dan lingkungan Desa/Kampung Wisata dan terdokumentasi.
LINGKUNGAN DAN PELESTARIAN|Kebijakan yang mengatur upaya pelestarian lingkungan hidup (bisa ditambahkan dengan adanya peraturan tertulis/SK/Perdes, dsb).|Dokumen kebijakan pelestarian lingkungan dalam pengelolaan DEWI|Tidak terdapat aturan terkait pelestarian lingkungan hidup.~Terdapat aturan, namun sifatnya lisan.~Terdapat aturan tertulis namun belum dapat diterapkan dalam pengelolaan Desa/Kampung Wisata.~Terdapat aturan tertulis, dan dapat diterapkan dalam pengelolaan Desa/Kampung Wisata.
LINGKUNGAN DAN PELESTARIAN|Kebijakan yang mengatur upaya pelestarian budaya.|Dokumen kebijakan pelestarian budaya dalam pengelolaan DEWI|Tidak terdapat aturan terkait pelestarian budaya.~Terdapat aturan, namun sifatnya lisan.~Terdapat aturan tertulis namun belum dapat diterapkan dalam pengelolaan Desa/Kampung Wisata.~Terdapat aturan tertulis, dan dapat diterapkan dalam pengelolaan Desa/Kampung Wisata.
LINGKUNGAN DAN PELESTARIAN|Adanya kelembagaan yang mengurusi pelestarian lingkungan di Desa/Kampung Wisata.|Dokumen struktur lembaga yang bertanggung jawab dalam pelestarian lingkungan|Tidak ada kelembagaan pelestarian lingkungan.~Terdapat kelembagaan pelestarian lingkungan, namun job desc-nya tidak hanya berfokus pada Desa/Kampung Wisata.~Terdapat kelembagaan pelestarian lingkungan dalam struktur Desa/Kampung Wisata, namun peran dan tanggung jawab masih tumpang tindih.~Terdapat kelembagaan pelestarian lingkungan di dalam struktur Desa/Kampung Wisata yang memiliki struktur organisasi, peran, dan tanggung jawab jelas.
LINGKUNGAN DAN PELESTARIAN|Adanya kelembagaan yang mengurusi pelestarian budaya di Desa/Kampung Wisata (dibuktikan dengan SK, HAKI, Nomer Induk Kebudayaan).|Dokumen struktur lembaga yang bertanggung jawab dalam pelestarian budaya|Tidak terdapat kelembagaan pelestarian budaya (paguyuban).~Terdapat kelembagaan pelestarian budaya, namun job desc-nya tidak hanya berfokus pada Desa/Kampung Wisata.~Terdapat kelembagaan pelestarian budaya dalam Desa/Kampung Wisata, ada struktur namun peran dan tanggung jawab masih tumpang tindih.~Terdapat kelembagaan pelestarian budaya, terdapat struktur organisasi serta peran dan tanggung jawab jelas, dibuktikan dengan SK, HAKI, atau NIK.
LINGKUNGAN DAN PELESTARIAN|Adanya fasilitas guna melestarikan budaya dan lingkungan di Desa/Kampung Wisata (latihan dan pertunjukan).|Data fasilitas yang diperuntukkan untuk pelestarian budaya dan dokumen pengelolaannya|Tidak terdapat fasilitas pelestarian di Desa/Kampung Wisata (sanggar/padepokan seni).~Terdapat fasilitas penunjang (sanggar/padepokan), namun bersifat insidentil atau menumpang di sanggar Desa/Kampung Wisata lain.~Terdapat fasilitas penunjang (sanggar/padepokan), namun tidak ada pengelolaan yang terorganisasi.~Terdapat fasilitas penunjang (sanggar/padepokan), ada struktur organisasi serta peran dan tanggung jawabnya.
LINGKUNGAN DAN PELESTARIAN|Pelestarian budaya lokal melalui event/pementasan.|Data pelaksanaan event, meliputi agenda event, event yang sudah dan akan dilaksanakan|Tidak terdapat event/pementasan dari masyarakat lokal.~Terdapat budaya lokal yang dijalankan namun hanya sebagai pelaksanaan acara adat setempat dan tidak dibuka untuk wisatawan.~Terdapat event/pementasan tapi pelaksanaannya tidak kontinyu, atau hanya sebatas permintaan pengunjung.~Terdapat event/pementasan, selain sebagai paket wisata juga sebagai bagian dari agenda rutin dari Desa/Kampung Wisata.
LINGKUNGAN DAN PELESTARIAN|Adanya kegiatan pelatihan budaya rutin.|Data program pelatihan budaya|Tidak terdapat kegiatan pelatihan budaya.~Terdapat kegiatan pelatihan budaya namun hanya ditujukan untuk pelestarian budaya warga setempat.~Terdapat kegiatan pelatihan budaya, namun event/pementasannya bergantung pada permintaan wisatawan (incidental).~Terdapat kegiatan pelatihan budaya yang dilakukan secara rutin dan merupakan atraksi wisata.
LINGKUNGAN DAN PELESTARIAN|Paket wisata yang mendukung kegiatan pelestarian lingkungan dan budaya|Data paket wisata yang mendukung pelestarian budaya|Tidak terdapat paket wisata yang terkait pada pelestarian lingkungan dan budaya.~Terdapat paket wisata yang menunjang pelestarian, namun bukan mejadi bagian utama dalam atraksi di Desa/Kampung Wisata.~Terdapat paket wisata yang menunjang pelestarian, namun pelaksanaannya tidak rutin/ sesuai permintaan pengunjung.~Paket wisata yang terkait dengan pelestarian, dijadikan sebagai bagian utama dalam atraksi di Desa/Kampung Wisata.
LINGKUNGAN DAN PELESTARIAN|Adanya sistem pengelolaan dan atau pengolahan limbah cair dan padat di Desa/Kampung Wisata (pemilahan sampah rumah tangga, bank sampah, pengolahan limbah cair sederhana).|Data program pengelolaan sampah|Tidak terdapat sistem pengolahan limbah.~Hanya terdapat tempat pembuangan sampah, namun belum tersistem dalam pengelolaan sampah yang terorganisasi.~Terdapat sistem pengolahan sampah, namun tidak memberikan keuntungan bagi masyarakat.~Terdapat sistem pengolahan sampah, pengelolaannya terorganisasi, dan memberikan keuntungan bagi masyarakat.
LINGKUNGAN DAN PELESTARIAN|Ada pengetahuan, pemahaman serta ada dukungan kelembagaan terkait kerentanan terhadap bahaya di sekitar kawasan.|Dokumen Penanggulangan Resiko Bencana. Ada signage khusus: jalur evakuasi, ancaman bencana, titik kumpul, shelter (jika ada) Ada lembaga penanggulangan bencana di tingkat desa/kampung|Tidak memiliki pengetahuan, pemahaman bila daerahnya termasuk wilayah rawan bencana.~Memiliki pemahaman bila daerah wisatanya termasuk rawan bencana, namun tidak ada tim/lembaga yg secara khusus dibentuk (Tagana) untuk itu.~Memiliki pemahaman bila daerah wisatanya termasuk rawan bencana, sudah ada tim/lembaga yg secara khusus dibentuk (Tagana) untuk itu. Dilokasi wisata sudah dilengkapi signage (penanda) jalur evakuasi, ancaman bencana, dan titik kumpul. Namun, belum memiliki dokumen penanggulangan resiko bencana (PRB).~Memiliki pemahaman bila daerah wisatanya termasuk rawan bencana, sudah ada tim/lembaga yg secara khusus dibentuk (Tagana) untuk itu. Dilokasi wisata sudah dilengkapi signage (penanda) jalur evakuasi, ancaman bencana, dan titik kumpul. Sudah memiliki dokumen penanggulangan resiko bencana (PRB).
PERAN SERTA MASYARAKAT|Tingkat keterlibatan masyarakat dalam program pengelolaan Desa/Kampung Wisata.|Data tingkat keterlibatan masyarakat dan bidang keterlibatan|Masyarakat tidak terlibat dalam pengelolaan Desa/Kampung Wisata.~Masyarakat hanya terlibat pada saat operasional saja.~Masyarakat dilibatkan dari proses perencanaan, operasional, pengambilan keputusan, sampai dengan monitoring dan evaluasi, namun tidak terdokumentasikan.~Masyarakat dilibatkan dari proses perencanaan, operasional, pengambilan keputusan, sampai dengan monitoring dan evaluasi, serta terdokumentasikan.
PERAN SERTA MASYARAKAT|Keterlibatan masyarakat dalam pemodalan untuk mendukung pengembangan Desa/Kampung Wisata.|Data pemodalan yang berasal dari masyarkat setempat|Tidak ada pemodalan dari masyarakat setempat.~Terdapat pemodalan dari masyarakat namun relatif kecil.~Masyarakat turut andil memberikan modal baik berupa uang cash, maupun fasilitas lain, namun tidak terdokumentasikan.~Masyarakat turut andil memberikan modal baik berupa uang cash, maupun fasilitas lain, dan terdokumentasikan.
PERAN SERTA MASYARAKAT|Penyerapan tenaga kerja sebagai bagian dari pemberdayaan masyarakat.|Data peluang usaha baru dan penyerapan tenaga kerja|Tidak ada peluang usaha baru yang mampu menyerap tenaga kerja dari masyarakat setempat.~Peluang usaha hanya menyerap tenaga kerja dari kalangan tertentu.~Pengelolaan Desa/Kampung Wisata membuka peluang usaha, namun belum mampu menyerap banyak tenaga kerja dari masyarakat setempat.~Pengelolaan Desa/Kampung Wisata membuka peluang usaha dan menyerap banyak tenaga kerja dari masyarakat setempat.
ATRAKSI WISATA|Daya tarik wisata alam yang dimiliki Desa/Kampung Wisata.|Profile Desa/Kampung Wisata|Hanya memiliki satu daya tarik.~Memiliki 2-3 jenis daya tarik.~Memiliki 4-5 jenis daya tarik.~Memiliki lebih dari 5 jenis daya tarik.
ATRAKSI WISATA|Daya tarik wisata budaya yang dimiliki Desa/Kampung Wisata.|Profile Desa/Kampung Wisata|Hanya memiliki satu daya tarik.~Memiliki 2-3 jenis daya tarik.~Memiliki 4-5 jenis daya tarik.~Memiliki lebih dari 5 jenis daya tarik.
ATRAKSI WISATA|Terdapat daya tarik wisata buatan yang disesuaikan dengan karakteristik lokal sebagai pendukung di Desa/Kampung Wisata.|Profile Desa/Kampung Wisata|Hanya memiliki satu daya tarik.~Hanya memiliki 2-3 jenis daya tarik.~Memiliki 4-5 jenis daya tarik.~Memiliki lebih dari 5 jenis daya tarik.
ATRAKSI WISATA|Terdapat paket wisata yang menghubungkan antar daya tarik alam, budaya, dan buatan.|Brosure Desa/Kampung Wisata|Belum ada paket wisata.~Terdapat paket wisata, namun tidak menghubungkan antar atraksi (setiap atraksi berjalan sendiri-sendiri).~Ada paket wisata hanya dua jenis (alam & budaya atau alam & buatan).~Terdapat paket wisata yang lengkap (menghubungkan semua atraksi).
ATRAKSI WISATA|Terdapat produk hasil industri kreatif (pengolahan produk lokal mejadi makanan, kerajinan tangan dsb) yang dapat mendukung kegiatan pariwisata.||Tidak terdapat produk hasil industri kreatif.~Terdapat produk hasil industri kreatif, namun tidak diorganisir sebagai produk wisata.~Terdapat produk hasil industri kreatif yang terorganisir, namun bergantung pesanan dari wisatawan.~Terdapat produk hasil industri kreatif, dan diorganisir sebagai produk/paket wisata.
ATRAKSI WISATA|Terdapat kehidupan sosial budaya (living cultur) yang khas melengkapi atraksi. Masih dijalankan tradisi yang dilestarikan dan telah dikemas menjadi atraksi budaya pendukung Desa/Kampung Wisata (event tahunan yang rutin dijalankan).||Tidak terdapat kehidupan sosial budaya dalam kehidupan Desa/Kampung Wisata.~Terdapat kehidupan sosial budaya, namun belum menjadi bagian dari atraksi.~Terdapat tradisi yang dijalankan sebagai atraksi budaya, namun bergantung pada permintaan wisatawan.~Terdapat tradisi yang terus berkembang menjadi sebuah atraksi terorganisasi sehingga masyarakat dan menjadi bagian dari paket wisata.
ATRAKSI WISATA|Terdapat event/kegiatan yang rutin dilaksanakan (misal pasar sabtu-minggu) di Desa/Kampung Wisata menyajikan sajian setempat dan telah menjadi atraksi pariwisata.||Tidak terdapat event/kegiatan rutin.~Terdapat event/kegiatan yang menyajikan sajian setempat tapi bukan sebagai produk wisata.~Terdapat event yang menjadi atraksi wisata, namun terdapat inkonsistensi pelaksanaan (kadang dilaksanakan sesuai keinginan pengelola).~Terdapat event rutin yang dijadikan atraksi wisata sebagai kegiatan terstruktur (terorganisir oleh pengelola dan masyarakat setempat).
ATRAKSI WISATA|Memiliki karakter daya tarik khusus yang menjadi USP (Unique Selling Point ).||Tidak memiliki daya tarik khusus.~Memiliki daya tarik khusus namun, Tidak memiliki karakter (cenderung latah, dan memiliki kesamaan dengan Desa/Kampung Wisata lain).~Memiliki daya tarik khusus unggulan, namun tidak terawat dan tidak strategis.~Memiliki daya tarik khusus dengan karakter dan USP yang kuat.
AKSESBILITAS|Tersedianya rambu penunjuk arah menuju dan di dalam Desa/Kampung Wisata.||Tidak terdapat rambu penunjuk arah menuju Desa/Kampung Wisata.~Terdapat hanya satu rambu penunjuk arah di jalan provinsi/kabupaten menuju Desa/Kampung Wisata.~Terdapat 2-3 rambu penunjuk arah di jalan provinsi/kabupaten hingga menuju Desa/Kampung Wisata.~Terdapat setidaknya 5 penunjuk arah yang informatif terpasang di jalan provinsi hingga menuju Desa/Kampung Wisata hingga ke sekretariat.
AKSESBILITAS|Tersedianya akses jalan menuju dan di dalam Desa/Kampung Wisata dalam kondisi baik, tidak berlobang, dan mudah dilalui berbagai moda transportasi.||Jalan tanah/beraspal dengan keadaan buruk, berlobang, dan hanya bisa diakses dengan jalan kaki.~Jalan tanah/beraspal dengan kondisi sedang sedikit berlobang, hanya bisa dilalui moda transportasi darat beroda 2 dan 4 saja.~Jalan beraspal keadaan baik, tidak berlobang, serta mudah dilalui moda transportasi kendaraan roda 2 dan 4 (atau lebih) namun belum tersedia lahan parkir yang representatif.~Jalan beraspal keadaan baik, tidak berlobang, serta mudah dilalui moda transportasi kendaraan roda 2 dan 4 (atau lebih) dan tersedianya lahan parkir yang memuat semua jenis moda transportasi.
AKSESBILITAS|Memiliki peta kawasan yang mudah ditemukan wisatawan di kawasan desa.||Tidak memiliki peta kawasan Desa/Kampung Wisata.~Memiliki peta kawasan Desa/Kampung Wisata, namun tidak dapat dilihat secara fisik (hanya versi digital saja).~Memiliki peta kawasan Desa/Kampung Wisata berwujud fisik yang letaknya bisa dijangkau tamu di satu titik.~Memiliki peta kawasan Desa/Kampung Wisata berwujud fisik yang letaknya bisa dijangkau tamu dan disediakan di beberapa titik dan disediakan akses peta digital (QR code/link).
AKSESBILITAS|Terdapat informasi titik lokasi di Google Maps yang disertai dengan gambar, data kontak yang bisa dihubungi, dan rating kepuasan pelayanan.||Tidak terdapat titik lokasi sekretariat Desa/Kampung Wisata di Google Maps.~Terdapat titik lokasi sekretariat Desa/Kampung Wisata di Google Maps namun tidak akurat.~Terdapat titik lokasi sekretariat Desa/Kampung Wisata di Google Maps yang akurat, disertai dengan gambar pendukung dan kontak yang bisa dihubungi.~Terdapat titik lokasi sekretariat Desa/Kampung Wisata di Google Maps yang akurat, disertai dengan gambar pendukung, kontak yang bisa dihubungi, dan rating kepuasan layanan dari tamu.
AKSESBILITAS|Terdapat penerangan jalan di malam hari.||Tidak terdapat penerangan jalan di malam hari di area kampung/desa wisata.~Terdapat penerangan jalan di malam hari hanya di 5-10 titik saja (jarak antar penerangan jalan lebih dari 25 meter) di area kampung/desa wisata.~Terdapat penerangan jalan di malam hari hanya di 11-20 titik saja (jarak antar penerangan jalan sekitar 10-15 meter) di area kampung/desa wisata.~Terdapat penerangan jalan di malam hari di semua area Desa/Kampung Wisata lebih dari 20 titik (dari pintu masuk, tikungan jalan, dan di dalam Desa/Kampung Wisata).
AKSESBILITAS|Tersedianya titik kumpul dan papan petunjuk menuju titik kumpul untuk evakuasi jika terjadi bencana.||Tidak tersedia titik kumpul untuk evakuasi jika terjadi bencana maupun papan petunjuk menuju titik kumpul.~Tersedia titik kumpul untuk evakuasi jika terjadi bencana tetapi belum tersedia papan petunjuk menuju titik kumpul.~Tersedia titik kumpul untuk evakuasi jika terjadi bencana dan tersedia papan petunjuk menuju titik kumpul hanya 1 buah.~Tersedia titik kumpul untuk evakuasi jika terjadi bencana dan tersedia papan petunjuk menuju titik kumpul lebih dari 2 buah.
AKSESBILITAS|Tersedianya layanan untuk wisatawan dengan disabilitas.||Tidak memiliki fasiltas untuk wisatawan dengan disabilitas.~Memiliki fasilitas ram untuk akses kursi roda di beberapa titik.~Memiliki fasilitas ram akses kursi roda di beberapa titik dan pemandu bahasa isyarat.~Memiliki fasilitas ram akses kursi roda di beberapa titik, pemandu bahasa isyarat, dan beberapa informasi dengan tulisan braile.
AMENITAS PENDUKUNG|Fasilitas dan proses penyediaan makanan dan minuman yang hiegienis.||Tidak memiliki fasilitas penyediaan makanan dan minuman yang higienis.~Memiliki fasilitas penyediaan makanan dan minuman yang hiegienis tetapi tidak ada standar penyediaan makanan dan minuman yang hieginis.~Memiliki fasilitas penyediaan makanan dan minuman yang hiegienis dan ada standar penyediaan makanan dan minuman yang higienis.~Memiliki sertifikasi penyediaan makanan dan minuman secara higienis.
AMENITAS PENDUKUNG|Penyediaan makanan dan minuman khas, yang menjadi keunikan Desa/Kampung Wisata.||Tidak mampu menyediakan makanan dan minuman khas lokal.~Mampu menyediakan makanan dan minuman, namun bukan khas lokal (hampir memiliki kesamaan dengan Desa/Kampung Wisata lainnya) dan penyajian ala kadarnya.~Mampu menyediakan makanan dan minuman khas lokal, namun penyajiannya ala kadarnya.~Mampu menyediakan makanan dan minuman khas lokal dalam kemasan yang menarik.
AMENITAS PENDUKUNG|Terdapat kantor sekretariat Desa/Kampung Wisata.||Belum ada kantor sekretariat.~Tidak ada bangunan tersendiri, tapi menggunakan rumah salah satu warga secara temporal (sementara).~Tidak ada bangunan tersendiri, bergabung dengan kantor yang lain.~Ada kantor sekretariat tersendiri.
AMENITAS PENDUKUNG|Terdapat gerai yang menjual souvenir atau produk lokal wisata.||Tidak terdapat kios/gerai cinderamata.~Tidak terdapat kios/gerai cinderamata, namun terdapat penjualan yang dilakukan di sekretariat Desa/Kampung Wisata.~Terdapat kios/gerai cinderamata yang berlokasi di pusat pelayanan (kelurahan/kecamatan).~Terdapat kios/gerai cinderamata yang berada di Desa/Kampung Wisata dan dikelola oleh pengurus Desa/Kampung Wisata.
AMENITAS PENDUKUNG|Terdapat jaringan telekomunikasi/ internet di Desa/Kampung Wisata.||Tidak ada jaringan internet/ telekomunikasi di Desa/Kampung Wisata.~Terdapat koneksi jaringan internet/ telekomunikasi di Desa/Kampung Wisata namun tidak lancar untuk semua provider.~Koneksi jaringan internet/ telekomunikasi di Desa/Kampung Wisata hanya didominasi beberapa provider.~Koneksi jaringan internet/ telekomunikasi di Desa/Kampung Wisata lancar ( baik wifi maupun provider tertentu).
AMENITAS PENDUKUNG|Terdapat fasilitas dan mekanisme pertolongan pertama untuk menangani krisis kesehatan atau kecelakaan dalam kegiatan wisata.||Tidak terdapat fasilitas dan mekanisme.~Terdapat fasilitas kesehatan tetapi kurang memadai dan tidak ada mekanisme khusus untuk menangani krisis kesehatan dan kecelakaan.~Terdapat fasilitas kesehatan yang memadai dan tetapi tidak ada mekanisme khusus untuk menangani krisis kesehatan dan kecelakaan.~Terdapat fasilitas kesehatan yang memadai dan ada mekanisme yang jelas untuk menangani krisis kesehatan/ kecelakaan.
AMENITAS PENDUKUNG|Fasilitas kesehatan (kotak P3K) dan alat pemadam kebakaran tersedia di Desa/Kampung Wisata yang dirawat/evaluasi secara berkala.||Tidak tersedia fasilitas kesehatan berupa kotak P3K dan alat pemadam kebakaran.~Hanya terdapat salah satu antara kotak P3K maupun alat pemadam kebakaran.~Tersedia kotak P3K dan/atau alat pemadam kebakaran namun tidak dirawat (kadaluarsa, atau tidak lengkap isinya, dsb).~Tersedia kotak P3K dan alat pemadam kebakaran yang terawat.
AMENITAS PENDUKUNG|Terdapat jaringan arus listrik cadangan ketika terjadi pemadaman (genset, tenaga listrik sederhana).||Tidak ada jaringan arus listrik cadangan ketika terjadi pemadaman.~Ada tenaga listrik cadangan di pusat sekretariat ataupun di balai pertemuan.~Ada tenaga listrik cadangan di pusat sekretariat ataupun di balai pertemuan serta lampu darurat di setiap homestay.~Ada generator sebagai arus listrik cadangan ketika terjadi pemadaman di setiap bangunan di Desa/Kampung Wisata.
AMENITAS PENDUKUNG|Terdapat sarana air bersih yang baik di Desa/Kampung Wisata.||Mengambil salah satu sumber air seperti, air tanah (sumur) / air gunung / mata air dengan menggunakan pipa sederhana hasil gotong royong warga.~Tersedia air namun hanya mengandalkan air tanah (sumur)/ air gunung/mata air yang disalurkan melalui pipa buatan ke setiap rumah warga.~Sudah tersedia jaringan air terpusat (tandon/ penampungan kecil) dari sumber air, maupun dari PDAM, secara merata ke rumah dan ke wahana yang medukung atraksi wisata.~Sudah tersedia jaringan air terpusat dari sumber air, ataupun dari PDAM, secara merata ke rumah dan ke wahana yang medukung atraksi wisata. Dan memiliki tampungan berupa embung / danau sebagai cadangan air untuk Desa/Kampung Wisata.
AMENITAS PENDUKUNG|Terdapat area parkir yang aman dan memadai di Desa/Kampung Wisata.||Desa/Kampung Wisata tidak memiliki area parkir.~Desa/Kampung Wisata memiliki area parkir yang dapat menampung roda 2.~Desa/Kampung Wisata memiliki area parkir yang dapat menampung roda 2 dan roda 4.~Desa/Kampung Wisata memiliki area parkir yang dapat menampung roda 2, roda 4, dan bus pariwisata.
AMENITAS PENDUKUNG|Terdapat lahan terbuka publik (lapangan atau panggung) yang dapat digunakan aktivitas wisata di Desa/Kampung Wisata.||Tidak ada lahan terbuka publik untuk kegiatan aktivitas wisata.~Terdapat lahan terbuka namun, bukan barang inventaris Desa/Kampung Wisata itu sendiri.~Terdapat lahan terbuka publik, milik Desa/Kampung Wisata, tapi tidak digunakan untuk aktivitas wisata.~Terdapat lahan terbuka publik, milik Desa/Kampung Wisata, dan digunakan untuk aktivitas wisata dan keperluan pribadi dari Desa/Kampung Wisata.
AMENITAS PENDUKUNG|Terdapat sarana peribadatan bagi pengunjung.||Tidak terdapat sarana peribadatan bagi pengunjung.~Terdapat fasilitas tempat peribadatan tetapi tidak tersedia alat peribadatan.~Terdapat fasilitas tempat peribadatan dan tersedia alat peribadatan, namun bercampur dengan bangunan lain.~Terdapat fasilitas tempat peribadatan dan tersedia alat peribadatan, dan memiliki bangunan sendiri.
AMENITAS PENDUKUNG|Mampu menyediakan kamar mandi dengan fasilitas kloset duduk di Desa/Kampung Wisata.||Belum tersedia fasilitas MCK publik.~Tersedia fasilitas MCK publik (dan/atau di rumah warga) dan belum ada fasilitas kloset duduk.~Tersedia fasilitas MCK publik dan tersedia fasilitas kloset duduk.~Tersedia fasilitas MCK publik dan tersedia fasilitas kloset duduk, dan terdapat MCK untuk penyandang disabilitas.
AMENITAS PENDUKUNG|Sudah tersedia rumah warga yang difungsikan sebagai homestay (sebutkan jumlah homestay).||Tidak ada homestay.~Terdapat homestay namun penggunaannya insidentil.~Terdapat homestay, terdapat kerjasama dengan pengelola Desa/Kampung Wisata, namun wisatawan terpisah dengan induk semang.~Terdapat homestay, terdapat kerjasama dengan pengelola Desa/Kampung Wisata, wisatawan bergabung dengan induk semang.
PROMOSI DAN PEMASARAN|Desa/Kampung Wisata memiliki kemitraan / MOU dengan Industri Biro perjalanan wisata dan asosiasi industri lainya serta Kemitraan yang berlangsung jangka waktu tertentu dan berkelanjutan.||Tidak memiliki kemitraan / MOU dengan industri diluar 3 unsur tsb serta terdokumentasikan.~Memiliki kemitraan / MOU dengan industri minimal mencakup 1 unsur serta terdokumentasikan.~Memiliki kemitraan / MOU dengan industri minimal mencakup 2 unsur serta terdokumentasikan.~Memiliki kemitraan / MOU dengan industri minimal mencakup 3 unsur (Pengembangan promosi & pemasaran , produk & layanan , penjualan) serta terdokumentasikan.
PROMOSI DAN PEMASARAN|Desa/Kampung Wisata menggunakan system digitalize dalam melakukan kegiatan promosi & pemasaran.||Desa/Kampung Wisata sudah menggunakan system digital Promotion 1 unsur.~Desa/Kampung Wisata sudah menggunakan system digital Promotion 2 unsur.~Desa/Kampung Wisata sudah menggunakan system digital Promotion 3 unsur.~Desa/Kampung Wisata sudah menggunakan system digital Promotion 4 unsur ( Website, Blog, sosial media: youtub-FB-IG, Online Travel ).
PROMOSI DAN PEMASARAN|Desa/Kampung Wisata active melakukan direct promotion melalui beberapa forum promosi ( B2B, sales trip, expo,tourism forum ).||Desa/Kampung Wisata active melakukan direct promotion melalui beberapa forum promosi mencakup 1 unsur.~Desa/Kampung Wisata active melakukan direct promotion melalui beberapa forum promosi mencakup 2 unsur.~Desa/Kampung Wisata active melakukan direct promotion melalui beberapa forum promosi mencakup 3 unsur.~Desa/Kampung Wisata active melakukan direct promotion melalui beberapa forum promosi mencakup 4 unsur ( B2B, sales trip, expo, tourism forum ).
PROMOSI DAN PEMASARAN|Desa/Kampung Wisata dengan Dinas Pariwisata dan instansi terkait mengadakan kegiatan famtrip dalam upaya lebih memperkenalkan dan mempromosikan serta memasarkan produknya terhadap potensial market / pasar.||Desa/Kampung Wisata dengan Dinas Pariwisata dan instansi terkait mengadakan kegiatan famtrip belum sesuai antara potensi dan marketnya serta belum dilakukan secara berkala/ periodic dalam 1 tahun.~Desa/Kampung Wisata dengan Dinas Pariwisata dan instansi terkait mengadakan kegiatan famtrip belum sesuai antara potensi dan marketnya namun sudah dilakukan secara berkala/ periodic dalam 1 tahun.~Desa/Kampung Wisata dengan Dinas Pariwisata dan instansi terkait mengadakan kegiatan famtrip sesuai antara potensi dan marketnya namun belum dilakukan secara berkala / periodic dalam 1 tahun.~Desa/Kampung Wisata dengan Dinas Pariwisata dan instansi terkait mengadakan kegiatan famtrip sudah sesuai antara potensi dan marketnya dan sudah melakukannya secara berkala / periodic dalam 1 tahun.
ROWS;
}
